---
title: "SARS-CoV-2 introduction and spread in connected systems"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{SARS-CoV-2 introduction and spread in connected systems}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r setup, include = FALSE}
library(whitetailedSIRS)
library(tidyverse)
library(deSolve)
library(rootSolve)
library(binom)
library(kableExtra)
```

```{r base_simulations, include = FALSE}
set.seed(23)
nsamples <- 200
I_human_null <- 0.05
times <- seq(0, 120, by = 1)
```


```{r, include = FALSE}
elicitation_data <- draw_elicitation_samples(nsamples = nsamples)
```

```{r Ranch Proximity, include = FALSE}
nWild <- rpois(nsamples,1000) #Abundance
A_w <- 100 #Area
habitat <- "med" #Habitat classification
sigma_season <- 1 #Season adjustment for proximity rate

sigma_dc <- get_EE_param_vals(data = elicitation_data, my_param = "Direct Contact Probability") #Probability of direct contact between deer, given proximity.
```

```{r, include = FALSE}
c_ww_ranch <- rep(0, nsamples) #Deer-to-deer proximity rate in wild (set to 0; events per day).
c_cw_null <- rep(0, nsamples) #Deer-to-deer proximity rate along fenceline (set to 0; events per day).
c_cc_ranch <- calc_contact_rate(nsamples = nsamples, type_contact = habitat, N_w = nWild)*(get_EE_param_vals(data = elicitation_data, my_param = "Proximity rate with baiting (17 events without baiting)")/17) #Deer-to-deer proximity rate in ranch context, mimicing wild proximity rates with the influence of baiting (events per day).

c_hw_ranch <- rep(0, nsamples) #Human-to-deer proximity rate in wild (set to 0; events per day).
c_hc_ranch <- get_EE_param_vals(data = elicitation_data, my_param = "Deer-Human Proximity Rate, Suburban (per 120 days)") /120 #Human-to-deer proximity rate in ranch context, mimicing suburban proximitty rates (events per day).
```

```{r common infection parameters, include = FALSE}
C_nu_human <- rnorm(n = nsamples, mean = 10^5.6, sd = 10^1.2)#viral load in humans (genomic copies per ml)
C_nu_deer <- 10^5.6 * get_EE_param_vals(data = elicitation_data, my_param = "Viral Load") #viral load in deer saliva, relative to humans (genomic copies per ml)

r_deer <- get_EE_param_vals(data = elicitation_data, my_param = "Dose-Response")# Dose response coefficient for deer and SARS-CoV-2
```

``` {r infection probability, include = FALSE}
#Infection probability calculation of aerosol transmission from deer-to-deer
t_contact_deer_deer_null <- get_EE_param_vals(data = elicitation_data, my_param = "Deer Proximity Duration (minutes)") #Estimate duration of proximity event...
nu_aero_deer_deer_ranch <- calc_nu_aero(C_nu = C_nu_deer,
                                        t_contact = t_contact_deer_deer_null / 60,
                                        r = r_deer, nsamples = nsamples) #...and estimate probability of infection given that duration of proximity event.

nu_aero_deer_deer_wild_null <- rep(0, nsamples) #Estimate infection probability in out in the wild as 0 (needs to be included for SIRS ODE equations)

#Infection probability of 0.1 ml of saliva being transferred between deer on contact
nu_dc_deer_deer_null <- calc_nu_dc(C_nu = C_nu_deer, nsamples = nsamples) #Calculate infection probability

#Infection probability calculation of aerosol transmission from humans-to-deer
t_contact_deer_human_ranch <- get_EE_param_vals(data = elicitation_data, my_param = "Deer-Human Proximity Duration, Captive (minutes)") #Estimate duration of human-deer proximity event in ranch facility context...
nu_aero_deer_human_ranch <- calc_nu_aero(ER = 0.53, C_nu = C_nu_human, 
                                        t_contact = t_contact_deer_human_ranch / 60,
                                        r = r_deer, nsamples = nsamples)#... and calculate infection probability given the duration of a human-deer proximity event.
nu_aero_deer_human_wild_null <- rep(0, nsamples)#Estimate human-to-deer infection probability out in the wild as 0 (needs to be included for SIRS ODE equations)

```

```{r, include = FALSE}
gamma_recov <- rep(1/6, nsamples)
alpha_immunity_null <- 1 / get_EE_param_vals(data = elicitation_data, my_param = 'Temporary Immunity')
```

```{r Ranch Compiler, include = FALSE}
captive.inits <- initial_compartments(S_wild_prop = 0, draws = nsamples)

ranch.params <- alternative(alpha_immunity = alpha_immunity_null,
                            c_ww = c_ww_ranch, c_cw = c_cw_null,c_cc = c_cc_ranch,
                            c_hw = c_hw_ranch, c_hc = c_hc_ranch,
                            nu_aero_deer_deer_wild = nu_aero_deer_deer_wild_null, nu_aero_deer_deer_captive = nu_aero_deer_deer_ranch, nu_aero_deer_human_wild = nu_aero_deer_human_wild_null, nu_aero_deer_human_capt = nu_aero_deer_human_ranch, sigma_dc = sigma_dc, nu_dc_deer_deer = nu_dc_deer_deer_null, gamma_recov = gamma_recov, I_human = rep(I_human_null, nsamples), boost = rep(0, nsamples))

proj.ranch <- run(iter = nsamples, initial_compartments = captive.inits, parameters = ranch.params, times = times, name = "Outdoor ranch")
```

```{r intensive captive, include = FALSE}
c_ww_intensive <- rep(0, nsamples)
c_cc_intensive <- get_EE_param_vals(data = elicitation_data, my_param = "Deer-Deer Proximity Rate, Captive (per day)")
c_hw_intensive <- rep(0, nsamples)
c_hc_intensive <- get_EE_param_vals(data = elicitation_data, my_param = "Deer-Human Proximity Rate, Suburban (per 120 days)") /120

nu_aero_deer_deer_intensive <- calc_nu_aero(C_nu = C_nu_deer,
                                            t_contact = t_contact_deer_deer_null / 60,
                                            r = r_deer, nsamples = nsamples, AER = rep(1, nsamples))

t_contact_deer_human_intensive <- get_EE_param_vals(data = elicitation_data, my_param = "Deer-Human Proximity Duration, Captive (minutes)") 

nu_aero_deer_human_intensive <- calc_nu_aero(ER = 0.53, C_nu = C_nu_human, 
                                            t_contact = t_contact_deer_human_intensive / 60,
                                            r = r_deer, nsamples = nsamples, AER = rep(1, nsamples))

intensive.params <- alternative(
   c_ww = c_ww_intensive, c_cw = c_cw_null, c_cc = c_cc_intensive, 
   c_hw = c_hw_intensive, c_hc = c_hc_intensive, 
   nu_aero_deer_deer_wild = nu_aero_deer_human_wild_null, nu_aero_deer_deer_captive =  nu_aero_deer_deer_intensive, nu_aero_deer_human_wild = nu_aero_deer_human_wild_null, nu_aero_deer_human_capt = nu_aero_deer_human_intensive, nu_dc_deer_deer = nu_dc_deer_deer_null,
   alpha_immunity = alpha_immunity_null, sigma_dc = sigma_dc, gamma_recov = gamma_recov, I_human = rep(I_human_null, nsamples), boost = rep(0, nsamples))

proj.intensive <- run(iter = nsamples, initial_compartments = captive.inits, parameters = intensive.params, times = times, name = "Intensive facility")
```

```{r wild and rural, include = FALSE}
c_ww_rural <- calc_contact_rate(nsamples = nsamples, type_contact = habitat, N_w = nWild, sigma_season = 1)
c_cc_rural <- rep(0, nsamples)
c_hw_rural <- get_EE_param_vals(data = elicitation_data, my_param = "Deer-Human Proximity Rate, Rural (per 120 days)") /120
c_hc_rural <- rep(0, nsamples)

t_contact_deer_human_rural <- get_EE_param_vals(data = elicitation_data, my_param = "Deer-Human Proximity Duration, Rural (minutes)")

nu_aero_deer_deer_rural <- calc_nu_aero(C_nu = C_nu_deer,
                                        t_contact = t_contact_deer_deer_null / 60,
                                        r = r_deer, nsamples = nsamples, AER = rep(4, nsamples))

nu_aero_deer_deer_captive_null <- rep(0, nsamples)

nu_aero_deer_human_rural <- calc_nu_aero(ER = 0.53, C_nu = C_nu_human, 
                                        t_contact = t_contact_deer_human_rural / 60,
                                        r = r_deer, nsamples = nsamples, AER = rep(4, nsamples))

nu_aero_deer_human_captive_null <- rep(0, nsamples)

wild.inits <- initial_compartments(S_captive_prop = 0, draws = nsamples)

rural.params <- alternative(c_ww = c_ww_rural, c_cw = c_cw_null, c_cc = c_cc_rural, c_hw = c_hw_rural, c_hc = c_hc_rural, nu_aero_deer_deer_wild = nu_aero_deer_deer_rural, nu_aero_deer_deer_captive = nu_aero_deer_deer_captive_null, nu_aero_deer_human_wild = nu_aero_deer_human_rural,  nu_aero_deer_human_capt = nu_aero_deer_human_captive_null, nu_dc_deer_deer = nu_dc_deer_deer_null,alpha_immunity = alpha_immunity_null, sigma_dc = sigma_dc, gamma_recov = gamma_recov, I_human = rep(I_human_null, nsamples), boost = rep(0, nsamples))

proj.rural <- run(iter = nsamples, initial_compartments = wild.inits, parameters = rural.params, times = times, name = "Wild, rural")
```

```{r wild and captive, include = FALSE}
c_ww_suburban <- calc_contact_rate(nsamples = nsamples, type_contact = habitat, N_w = nWild, sigma_season = 1)
c_cc_suburban <- rep(0, nsamples)
c_hw_suburban <- get_EE_param_vals(data = elicitation_data, my_param = "Deer-Human Proximity Rate, Suburban (per 120 days)") /120
c_hc_suburban <- rep(0, nsamples)

t_contact_deer_human_suburban <- get_EE_param_vals(data = elicitation_data, my_param = "Deer-Human Proximity Duration, Suburban (minutes)")

nu_aero_deer_deer_suburban <- calc_nu_aero(C_nu = C_nu_deer,
                                        t_contact = t_contact_deer_deer_null / 60,
                                        r = r_deer, nsamples = nsamples, AER = rep(4, nsamples))

nu_aero_deer_human_suburban <- calc_nu_aero(ER = 0.53, C_nu = C_nu_human, 
                                        t_contact = t_contact_deer_human_suburban / 60,
                                        r = r_deer, nsamples = nsamples, AER = rep(4, nsamples))

suburban.params <- alternative(c_ww = c_ww_suburban, c_cw = c_cw_null, c_cc = c_cc_suburban, c_hw = c_hw_suburban, c_hc = c_hc_suburban, nu_aero_deer_deer_wild = nu_aero_deer_deer_suburban, nu_aero_deer_deer_captive = nu_aero_deer_deer_captive_null, nu_aero_deer_human_wild = nu_aero_deer_human_suburban,  nu_aero_deer_human_capt = nu_aero_deer_human_captive_null, nu_dc_deer_deer = nu_dc_deer_deer_null,alpha_immunity = alpha_immunity_null, sigma_dc = sigma_dc, gamma_recov = gamma_recov, I_human = rep(I_human_null, nsamples), boost = rep(0, nsamples))

proj.suburban <- run(iter = nsamples, initial_compartments = wild.inits, parameters = suburban.params, times = times, name = "Wild, suburban")
```

```{r, message=FALSE, include = FALSE}
sirs_results_contexts <- rbind(proj.ranch,proj.intensive, proj.rural, proj.suburban)

sirs_results_contexts %>%
  mutate(ode_df = map(ode_proj, as.data.frame)) %>%
  pull(ode_df) %>%
  list_rbind(names_to = "run_id") %>% 
  mutate(., Context = c(rep(unique(sirs_results_contexts$Context)[1],length(times)*nsamples),rep(unique(sirs_results_contexts$Context)[2],length(times)*nsamples), rep(unique(sirs_results_contexts$Context)[3],length(times)*nsamples),rep(unique(sirs_results_contexts$Context)[4],length(times)*nsamples))) %>% 
  group_by(Context, run_id) %>% 
  summarize(Wild = mean(I_wild), Captive = mean(I_captive), Infected = Wild + Captive, Persist_wild = last(I_wild) >=0.0001, Persist_captive = last(I_captive) >=0.0001, Persist = as.logical(Persist_wild + Persist_captive)) %>% 
  mutate(., Context = factor(Context, levels = c("Outdoor ranch", "Intensive facility", "Wild, rural","Wild, suburban"))) %>% 
   select(., -Wild, -Captive, -Persist_wild, -Persist_captive) %>% 
  group_by(.,Context) %>% 
  arrange(., Context, run_id) -> Prev_Persist_df
```


```{r, message=FALSE, warning=FALSE, include = FALSE}
ranch.df <- list_cbind(map(ranch.params, as_data_frame))
colnames(ranch.df) <-  names(ranch.params)
ranch.df %>% 
  mutate(., run_id = min(Prev_Persist_df[which(Prev_Persist_df$Context=="Outdoor ranch"),"run_id"])+0:(nsamples-1),r0 = unlist((beta_aero_ww+beta_aero_cc+beta_dc_ww+beta_dc_cc)/gamma_recov),
         FOI = unlist((beta_aero_hw+beta_aero_hc)*I_human),
         Context = "Outdoor ranch", Setting = "Captive") %>% 
  select(., run_id, Context,  Setting, r0, FOI) -> ranch.r0.FOI

intensive.df <- list_cbind(map(intensive.params, as_data_frame))
colnames(intensive.df) <-  names(intensive.params)
intensive.df %>% 
  mutate(., run_id = min(Prev_Persist_df[which(Prev_Persist_df$Context=="Intensive facility"),"run_id"])+0:(nsamples-1),r0 = unlist((beta_aero_ww+beta_aero_cc+beta_dc_ww+beta_dc_cc)/gamma_recov),
         FOI = unlist((beta_aero_hw+beta_aero_hc)*I_human),
         Context = "Intensive facility", Setting = "Captive") %>% 
  select(., run_id, Context,  Setting, r0, FOI) -> intensive.r0.FOI

rural.df <- list_cbind(map(rural.params, as_data_frame))
colnames(rural.df) <-  names(rural.params)
rural.df %>% 
  mutate(., run_id = min(Prev_Persist_df[which(Prev_Persist_df$Context=="Wild, rural"),"run_id"])+0:(nsamples-1),r0 = unlist((beta_aero_ww+beta_aero_cc+beta_dc_ww+beta_dc_cc)/gamma_recov),
         FOI = unlist((beta_aero_hw+beta_aero_hc)*I_human),
         Context = "Wild, rural", Setting = "Wild") %>% 
  select(., run_id, Context, Setting,  r0, FOI) -> rural.r0.FOI

suburban.df <- list_cbind(map(suburban.params, as_data_frame))
colnames(suburban.df) <-  names(suburban.params)
suburban.df %>% 
  mutate(., run_id = min(Prev_Persist_df[which(Prev_Persist_df$Context=="Wild, suburban"),"run_id"])+0:(nsamples-1),r0 = unlist((beta_aero_ww+beta_aero_cc+beta_dc_ww+beta_dc_cc)/gamma_recov),
         FOI = unlist((beta_aero_hw+beta_aero_hc)*I_human),
         Context = "Wild, suburban", Setting = "Wild") %>% 
  select(., run_id, Context, Setting, r0, FOI) -> suburban.r0.FOI

r0.FOI <- rbind(ranch.r0.FOI,intensive.r0.FOI, rural.r0.FOI,suburban.r0.FOI)

#Merge with average prevalence (step 1) and persistence (step 2)
merge(r0.FOI,Prev_Persist_df[,c("run_id","Infected", "Persist")], by = "run_id", all.x = TRUE) %>% 
  mutate(Context = factor(Context,  levels = c("Outdoor ranch", "Intensive facility", "Wild, rural","Wild, suburban"))) -> df
```

```{r, include = FALSE}
df %>% 
  group_by(., Context) %>% 
  reframe(., R0.Median = round(quantile(r0,probs = c(0.5)),2), FOI.Median = round(log10(quantile(FOI,probs = c(0.5))),2), Prevalence.Median = round(quantile(Infected, probs = c(0.5)),2), Persistence.Median = round(sum(Persist)/nsamples,2)) -> median.results

```
#COMBINED SYSTEMS

Ranch, Rural
```{r}
c_cw <- 0.00072 / get_EE_param_vals(data = elicitation_data, my_param = "Direct Contact Probability") #Deer-to-deer proximity rate along fenceline (events per day).

ranch_rural.inits <- initial_compartments(draws = nsamples)

ranch_rural.params <- alternative(alpha_immunity = alpha_immunity_null,
                            c_ww = c_ww_rural, c_cw = c_cw, c_cc = c_cc_ranch,
                            c_hw = c_hw_rural, c_hc = c_hc_ranch,
                            nu_aero_deer_deer_wild = nu_aero_deer_deer_rural, nu_aero_deer_deer_captive = nu_aero_deer_deer_ranch, nu_aero_deer_human_wild = nu_aero_deer_human_rural, nu_aero_deer_human_capt = nu_aero_deer_human_ranch, sigma_dc = sigma_dc, nu_dc_deer_deer = nu_dc_deer_deer_null, gamma_recov = gamma_recov, I_human = rep(I_human_null, nsamples), boost = rep(0, nsamples))

proj_ranch_rural <- run(iter = nsamples, initial_compartments = ranch_rural.inits, parameters = ranch_rural.params, times = times, name = "Outdoor ranch and rural system")
```

Ranch, Suburban
```{r}
ranch_suburban.inits <- initial_compartments(draws = nsamples)

ranch_suburban.params <- alternative(alpha_immunity = alpha_immunity_null,
                            c_ww = c_ww_suburban, c_cw = c_cw, c_cc = c_cc_ranch,
                            c_hw = c_hw_suburban, c_hc = c_hc_ranch,
                            nu_aero_deer_deer_wild = nu_aero_deer_deer_suburban, nu_aero_deer_deer_captive = nu_aero_deer_deer_ranch, nu_aero_deer_human_wild = nu_aero_deer_human_suburban, nu_aero_deer_human_capt = nu_aero_deer_human_ranch, sigma_dc = sigma_dc, nu_dc_deer_deer = nu_dc_deer_deer_null, gamma_recov = gamma_recov, I_human = rep(I_human_null, nsamples), boost = rep(0, nsamples))

proj_ranch_suburban <- run(iter = nsamples, initial_compartments = ranch_suburban.inits, parameters = ranch_suburban.params, times = times, name = "Outdoor ranch and suburban system")
```

Intensive, Rural
```{r}
intensive_rural.inits <- initial_compartments(draws = nsamples)

intensive_rural.params <- alternative(alpha_immunity = alpha_immunity_null,
                            c_ww = c_ww_rural, c_cw = c_cw, c_cc = c_cc_intensive,
                            c_hw = c_hw_rural, c_hc = c_hc_intensive,
                            nu_aero_deer_deer_wild = nu_aero_deer_deer_rural, nu_aero_deer_deer_captive = nu_aero_deer_deer_intensive, nu_aero_deer_human_wild = nu_aero_deer_human_rural, nu_aero_deer_human_capt = nu_aero_deer_human_intensive, sigma_dc = sigma_dc, nu_dc_deer_deer = nu_dc_deer_deer_null, gamma_recov = gamma_recov, I_human = rep(I_human_null, nsamples), boost = rep(0, nsamples))

proj_intensive_rural <- run(iter = nsamples, initial_compartments = intensive_rural.inits, parameters = intensive_rural.params, times = times, name = "Intensive facility and rural system")
```

Intensive, Suburban
```{r}
intensive_suburban.inits <- initial_compartments(draws = nsamples)

intensive_suburban.params <- alternative(alpha_immunity = alpha_immunity_null,
                            c_ww = c_ww_suburban, c_cw = c_cw, c_cc = c_cc_intensive,
                            c_hw = c_hw_suburban, c_hc = c_hc_intensive,
                            nu_aero_deer_deer_wild = nu_aero_deer_deer_suburban, nu_aero_deer_deer_captive = nu_aero_deer_deer_intensive, nu_aero_deer_human_wild = nu_aero_deer_human_suburban, nu_aero_deer_human_capt = nu_aero_deer_human_intensive, sigma_dc = sigma_dc, nu_dc_deer_deer = nu_dc_deer_deer_null, gamma_recov = gamma_recov, I_human = rep(I_human_null, nsamples), boost = rep(0, nsamples))

proj_intensive_suburban <- run(iter = nsamples, initial_compartments = intensive_suburban.inits, parameters = intensive_suburban.params, times = times, name = "Intensive facility and suburban system")
```

```{r}
proj.ranch %>%
  mutate(ode_df = map(ode_proj, as.data.frame)) %>%
  pull(ode_df) %>%
  list_rbind(names_to = "run_id") %>% 
  mutate(., Context = c(rep(unique(proj.ranch$Context)[1],length(times)*nsamples))) %>% 
  group_by(Context, run_id) %>% 
  summarize(Captive.Isolated = mean(I_captive), Persist_captive_isolated = last(I_captive) >=0.0001) %>% 
  mutate(., Context = factor(Context, levels = c("Outdoor ranch"))) %>% 
  group_by(.,Context) %>% 
  arrange(., Context, run_id) -> Prev_Persist_ranch_df

proj.intensive %>%
  mutate(ode_df = map(ode_proj, as.data.frame)) %>%
  pull(ode_df) %>%
  list_rbind(names_to = "run_id") %>% 
  mutate(., Context = c(rep(unique(proj.intensive$Context)[1],length(times)*nsamples))) %>% 
  group_by(Context, run_id) %>% 
  summarize(Captive.Isolated = mean(I_captive), Persist_captive_isolated = last(I_captive) >=0.0001) %>% 
  mutate(., Context = factor(Context, levels = c("Intensive facility"))) %>% 
  group_by(.,Context) %>% 
  arrange(., Context, run_id) -> Prev_Persist_intensive_df

proj.rural %>%
  mutate(ode_df = map(ode_proj, as.data.frame)) %>%
  pull(ode_df) %>%
  list_rbind(names_to = "run_id") %>% 
  mutate(., Context = c(rep(unique(proj.rural$Context)[1],length(times)*nsamples))) %>% 
  group_by(Context, run_id) %>% 
  summarize(Wild.Isolated = mean(I_wild), Persist_wild_isolated = last(I_wild) >=0.0001) %>% 
  mutate(., Context = factor(Context, levels = c("Wild, rural"))) %>%
  group_by(.,Context) %>% 
  arrange(., Context, run_id) -> Prev_Persist_rural_df

proj.suburban %>%
  mutate(ode_df = map(ode_proj, as.data.frame)) %>%
  pull(ode_df) %>%
  list_rbind(names_to = "run_id") %>% 
  mutate(., Context = c(rep(unique(proj.suburban$Context)[1],length(times)*nsamples))) %>% 
  group_by(Context, run_id) %>% 
  summarize(Wild.Isolated = mean(I_wild), Persist_wild_isolated = last(I_wild) >=0.0001) %>% 
  mutate(., Context = factor(Context, levels = c("Wild, suburban"))) %>%
  group_by(.,Context) %>% 
  arrange(., Context, run_id) -> Prev_Persist_suburban_df
```

```{r}
proj_ranch_rural %>%
  mutate(ode_df = map(ode_proj, as.data.frame)) %>%
  pull(ode_df) %>%
  list_rbind(names_to = "run_id") %>% 
  mutate(., Context = c(rep(unique(proj_ranch_rural$Context)[1],length(times)*nsamples))) %>% 
  group_by(Context, run_id) %>% 
  summarize(Wild = mean(I_wild), Captive = mean(I_captive), Persist_wild = last(I_wild) >=0.0001, Persist_captive = last(I_captive) >=0.0001) %>% 
  mutate(., Context = factor(Context, levels = c("Outdoor ranch and rural system"))) %>% 
  group_by(.,Context) %>% 
  arrange(., Context, run_id) -> Prev_Persist_ranch_rural_system_df

proj_ranch_suburban %>%
  mutate(ode_df = map(ode_proj, as.data.frame)) %>%
  pull(ode_df) %>%
  list_rbind(names_to = "run_id") %>% 
  mutate(., Context = c(rep(unique(proj_ranch_suburban$Context)[1],length(times)*nsamples))) %>% 
  group_by(Context, run_id) %>% 
  summarize(Wild = mean(I_wild), Captive = mean(I_captive), Persist_wild = last(I_wild) >=0.0001, Persist_captive = last(I_captive) >=0.0001) %>% 
  mutate(., Context = factor(Context, levels = c("Outdoor ranch and suburban system"))) %>% 
  group_by(.,Context) %>% 
  arrange(., Context, run_id) -> Prev_Persist_ranch_sub_system_df

proj_intensive_rural %>%
  mutate(ode_df = map(ode_proj, as.data.frame)) %>%
  pull(ode_df) %>%
  list_rbind(names_to = "run_id") %>% 
  mutate(., Context = c(rep(unique(proj_intensive_rural$Context)[1],length(times)*nsamples))) %>% 
  group_by(Context, run_id) %>% 
  summarize(Wild = mean(I_wild), Captive = mean(I_captive), Persist_wild = last(I_wild) >=0.0001, Persist_captive = last(I_captive) >=0.0001) %>% 
  mutate(., Context = factor(Context, levels = c("Intensive facility and rural system"))) %>% 
  group_by(.,Context) %>% 
  arrange(., Context, run_id) -> Prev_Persist_intensive_rural_system_df

proj_intensive_suburban %>%
  mutate(ode_df = map(ode_proj, as.data.frame)) %>%
  pull(ode_df) %>%
  list_rbind(names_to = "run_id") %>% 
  mutate(., Context = c(rep(unique(proj_intensive_suburban$Context)[1],length(times)*nsamples))) %>% 
  group_by(Context, run_id) %>% 
  summarize(Wild = mean(I_wild), Captive = mean(I_captive), Persist_wild = last(I_wild) >=0.0001, Persist_captive = last(I_captive) >=0.0001) %>% 
  mutate(., Context = factor(Context, levels = c("Intensive facility and suburban system"))) %>% 
  group_by(.,Context) %>% 
  arrange(., Context, run_id) -> Prev_Persist_intensive_sub_system_df
```

```{r}
#Calculate change in prevalence and persistence
#Ranch, rural
Prev_Persist_ranch_rural_system_df %>% 
   merge(., Prev_Persist_ranch_df, by = "run_id") %>% 
   merge(., Prev_Persist_rural_df, by = "run_id") %>% 
   select(., -Context.y, -Context) %>% 
   mutate(., Change_Prev_Wild = Wild - Wild.Isolated, Change_Prev_Captive = Captive - Captive.Isolated, Proportional_Change_Prev_Wild = Change_Prev_Wild/Wild.Isolated, Proportional_Change_Prev_Captive = Change_Prev_Captive/Captive.Isolated, Change_Persist_Wild = Persist_wild - Persist_wild_isolated, Change_Persist_Captive = Persist_captive - Persist_captive_isolated) %>% 
   select(., Context.x, Change_Prev_Wild, Change_Prev_Captive, Proportional_Change_Prev_Wild, Proportional_Change_Prev_Captive, Change_Persist_Wild, Change_Persist_Captive) %>% 
   rename(., System = Context.x) -> ranch_rural_results

#Ranch, suburban
Prev_Persist_ranch_sub_system_df %>% 
   merge(., Prev_Persist_ranch_df, by = "run_id") %>% 
   merge(., Prev_Persist_suburban_df, by = "run_id") %>% 
   select(., -Context.y, -Context) %>% 
   mutate(., Change_Prev_Wild = Wild - Wild.Isolated, Change_Prev_Captive = Captive - Captive.Isolated, Proportional_Change_Prev_Wild = Change_Prev_Wild/Wild.Isolated, Proportional_Change_Prev_Captive = Change_Prev_Captive/Captive.Isolated, Change_Persist_Wild = Persist_wild - Persist_wild_isolated, Change_Persist_Captive = Persist_captive - Persist_captive_isolated) %>% 
   select(., Context.x, Change_Prev_Wild, Change_Prev_Captive, Proportional_Change_Prev_Wild, Proportional_Change_Prev_Captive, Change_Persist_Wild, Change_Persist_Captive) %>% 
   rename(., System = Context.x) -> ranch_suburban_results

#Intensive, rural
Prev_Persist_intensive_rural_system_df %>% 
   merge(., Prev_Persist_intensive_df, by = "run_id") %>% 
   merge(., Prev_Persist_rural_df, by = "run_id") %>% 
   select(., -Context.y, -Context) %>% 
   mutate(., Change_Prev_Wild = Wild - Wild.Isolated, Change_Prev_Captive = Captive - Captive.Isolated, Proportional_Change_Prev_Wild = Change_Prev_Wild/Wild.Isolated, Proportional_Change_Prev_Captive = Change_Prev_Captive/Captive.Isolated, Change_Persist_Wild = Persist_wild - Persist_wild_isolated, Change_Persist_Captive = Persist_captive - Persist_captive_isolated) %>% 
   select(., Context.x, Change_Prev_Wild, Change_Prev_Captive, Proportional_Change_Prev_Wild, Proportional_Change_Prev_Captive, Change_Persist_Wild, Change_Persist_Captive) %>% 
   rename(., System = Context.x) -> intensive_rural_results

#Intensive, suburban
Prev_Persist_intensive_sub_system_df %>% 
   merge(., Prev_Persist_intensive_df, by = "run_id") %>% 
   merge(., Prev_Persist_suburban_df, by = "run_id") %>% 
   select(., -Context.y, -Context) %>% 
   mutate(., Change_Prev_Wild = Wild - Wild.Isolated, Change_Prev_Captive = Captive - Captive.Isolated, Proportional_Change_Prev_Wild = Change_Prev_Wild/Wild.Isolated, Proportional_Change_Prev_Captive = Change_Prev_Captive/Captive.Isolated, Change_Persist_Wild = Persist_wild - Persist_wild_isolated, Change_Persist_Captive = Persist_captive - Persist_captive_isolated) %>% 
   select(., Context.x, Change_Prev_Wild, Change_Prev_Captive, Proportional_Change_Prev_Wild, Proportional_Change_Prev_Captive, Change_Persist_Wild, Change_Persist_Captive) %>% 
   rename(., System = Context.x) -> intensive_suburban_results
```

```{r}
sirs_results_systems <- rbind(ranch_suburban_results,intensive_suburban_results,ranch_rural_results,intensive_rural_results)

sirs_results_systems %>% 
   group_by(., System) %>% 
   summarise(., Wild_Prevalence_Change = paste0(round(median(Change_Prev_Wild)*100,4), " (", round(quantile(Change_Prev_Wild,probs = 0.1)*100,4), "-",round(quantile(Change_Prev_Wild,probs = 0.9)*100,4),")"), Captive_Prevalence_Change = paste0(round(median(Change_Prev_Captive)*100,4), " (", round(quantile(Change_Prev_Captive,probs = 0.1)*100,4), "-",round(quantile(Change_Prev_Captive,probs = 0.9)*100,4),")"), 
             Wild_Prevalence_Proportional_Change = paste0(round(median(Proportional_Change_Prev_Wild)*100,4), " (", round(quantile(Proportional_Change_Prev_Wild,probs = 0.1)*100,4), "-",round(quantile(Proportional_Change_Prev_Wild,probs = 0.9)*100,4),")"), Proportional_Captive_Prevalence_Change = paste0(round(median(Proportional_Change_Prev_Captive)*100,4), " (", round(quantile(Proportional_Change_Prev_Captive,probs = 0.1)*100,4), "-",round(quantile(Proportional_Change_Prev_Captive,probs = 0.9)*100,4),")"),
             Wild_Persist_Change = paste0(round(binom.confint(sum(Change_Persist_Wild),nsamples,methods = "exact")$mean,2), " (", round(binom.confint(sum(Change_Persist_Wild),nsamples,methods = "exact", conf.level = 0.80)$lower,2), "-", round(binom.confint(sum(Change_Persist_Wild),nsamples,methods = "exact", conf.level = 0.80)$upper,2), ")"),
             Captive_Persist_Change = sum(Change_Persist_Captive)) ->fence_effect

fence_effect %>%
  kbl() %>%
  kable_paper("hover", full_width = T)
```
